# Generated by Django 5.2.6 on 2025-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball'), ('shoes', 'Shoes'), ('jersey', 'Jersey & Apparel'), ('accessories', 'Accessories'), ('bag', 'Bags')], default='ball', max_length=20),
        ),
    ]
